apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gp-app-0418 
  janus-idp.io/tekton: gp-app-0418
  backstage.io/kubernetes-id: gp-app-0418
  backstage.io/kubernetes-namespace: gp-app-0418 
  app.kubernetes.io/part-of: gp-app-0418
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  