apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gp-app-0418-gitops
  description: This is GitOps manifest for gp-app-0418   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: gp-app-0418
    janus-idp.io/tekton: gp-app-0418 
    backstage.io/kubernetes-id: gp-app-0418 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gp-app-0418
